# Generated by Django 2.1.7 on 2019-04-02 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_auth', '0002_auto_20190402_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test_auth.Team'),
        ),
    ]
